### ISSUE TITLE
Roadmap 1.x

### ISSUE THREAD

**Issue by simonostendorf** [simonostendorf/k3s-hetzner#24]
- [ ] Deploy kube-prometheus-stack (prometheus, grafana, alertmanager, node-exporter etc.) to collect and visualize metrics from nodes and pods
- [ ] Setup vertical pod autoscaler to automaticly update pod resources requests and limits
- [ ] Setup goldilocks as dashboard for the vertical pod autoscaler
- [x] #51
- [x] #50
- [ ] Use placement groups for agents for better availability (currently not possible because of the cluster autoscaler hetzner support)
- [ ] Allow connection to the kubernetes api and some services only with high-available vpn
- [ ] Setup more loadbalancers for separation of dev and production deployments and different access rights
